name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check
      run: make check

    - name: Test
      run: ./test.sh

  windows:
    strategy:
      matrix:
        arch: [amd64, x86]

        compiler: [mingw, msvc, llvm]

        exclude:
        - { arch: x86, compiler: llvm }

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup toolchain
      run: .github\toolchain.ps1 ${{ matrix.arch }} ${{ matrix.compiler }}

    - name: Test
      env:
        CLANG_VERSION_PREFIX: C:\Program Files\LLVM\lib\clang\19
        CLANG_EXTRA_FLAGS: " -Wno-unused-macros"
      shell: cmd
      run: |
        set arch=64
        if ${{ matrix.arch }} == x86 set arch=32
        if ${{ matrix.compiler }} == llvm set arch=
        set jtckdint_build_mode=${{ matrix.compiler }}%arch%
        call test.bat
